spring:

  application:
    name: LogMeal

  datasource:
    url: <>
    username: <>
    password: <>

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <>
            client-secret: <>


my-api-key: <>